name: Drive_Move
description: An application that allows you to quickly move files to drives
# version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  path: ^1.6.0
  process_run: ^0.10.7
  yaml: ^2.2.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
